ALTER TABLE products
ADD quantity INT NOT NULL DEFAULT 0;

ALTER TABLE products
ALTER COLUMN image VARCHAR(MAX) NOT NULL;

ALTER TABLE products
ADD CONSTRAINT DF_createdAt DEFAULT GETDATE() FOR createdAt;

ALTER TABLE products
ADD CONSTRAINT DF_updatedAt DEFAULT GETDATE() FOR updatedAt;

ALTER TABLE products
ALTER COLUMN createdAt DATETIME NOT NULL;

ALTER TABLE products
ALTER COLUMN updatedAt DATETIME NOT NULL;
